import HomeDefault from "./Home/HomeDefault";
import ProfileDefault from "./Profile/ProfileDefault";
import LoginDefault from "./Login/LoginDefault";
import SignUpDefault from "./SignUp/SignUpDefault";
import HotelsDefault from "./Hotels/HotelsDefault";
import HotelDetailsDefault from "./Hotels/HotelDetailsDefault";
import Flights_HomeDefault from "./Flights/Flights_HomeDefault";
import Flight_ListDefault from "./Flights/Flight_ListDefault";
import FlightDetailsDefault from "./Flights/FlightDetailsDefault";
import Restaurant_ListDefault from "./Restaurants/Restaurant_ListDefault";
import RestaurantDetailsDefault from "./Restaurants/RestaurantDetailsDefault";
import ThingsToDoDefault from "./ThingsToDo/ThingsToDoDefault";
import ThingsToDoDetailsDefault from "./ThingsToDo/ThingsToDoDetailsDefault";
import TripsDefault from "./Trip/TripsDefault";
import TripDetailsDefault from "./Trip/TripDetailsDefault";
import FavPlacesDefault from "./FavPlaces/FavPlacesDefault";
import ReservationsDefault from "./Reservations/ReservationsDefault";
import ItineraryDefault from "./Itinerary/ItineraryDefault";
import NotFoundDefault from "./NotFound/NotFoundDefault";
import CarRentalDefault from "./CarRental/CarRentalDefault";
import CreateTripDefault from "./CreateTrip/CreateTripDefault";

export { Home } from "./Home/Home";
export { Profile } from "./Profile/Profile";
export { Login } from "./Login/Login";
export { SignUp } from "./SignUp/SignUp";
export { Hotels } from "./Hotels/Hotels";
export { HotelDetails } from "./Hotels/HotelDetails";
export { Flights_Home } from "./Flights/Flights_Home";
export { Flight_List } from "./Flights/Flight_List";
export { FlightDetails } from "./Flights/FlightDetails";
export { Restaurant_List } from "./Restaurants/Restaurant_List";
export { RestaurantDetails } from "./Restaurants/RestaurantDetails";
export { ThingsToDo } from "./ThingsToDo/ThingsToDo";
export { ThingsToDoDetails } from "./ThingsToDo/ThingsToDoDetails";
export { Trips } from "./Trip/Trips";
export { TripDetails } from "./Trip/TripDetails";
export { FavPlaces } from "./FavPlaces/FavPlaces";
export { Reservations } from "./Reservations/Reservations";
export { Itinerary } from "./Itinerary/Itinerary";
export { NotFound } from "./NotFound/NotFound";
export { CarRental } from "./CarRental/CarRental";
export { CreateTrip } from "./CreateTrip/CreateTrip";
