let a = [
  { country: "Italy", geonameid: 3179977, name: "Cascina", subcountry: "Tuscany" },
  { country: "Italy", geonameid: 3180133, name: "Casamassima", subcountry: "Apulia" },
  {
    country: "Italy",
    geonameid: 3180172,
    name: "Casalnuovo di Napoli",
    subcountry: "Campania",
  },
  {
    country: "Italy",
    geonameid: 3180208,
    name: "Casale Monferrato",
    subcountry: "Piedmont",
  },
  {
    country: "Italy",
    geonameid: 3180224,
    name: "Casalecchio di Reno",
    subcountry: "Emilia-Romagna",
  },
  {
    country: "Italy",
    geonameid: 3180240,
    name: "Casal di Principe",
    subcountry: "Campania",
  },
  { country: "Italy", geonameid: 3180423, name: "Carrara", subcountry: "Tuscany" },
  {
    country: "Italy",
    geonameid: 3180445,
    name: "Carpi Centro",
    subcountry: "Emilia-Romagna",
  },
  { country: "Italy", geonameid: 3180496, name: "Carmagnola", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 3180541, name: "Cardito", subcountry: "Campania" },
  {
    country: "Italy",
    geonameid: 3180581,
    name: "Carate Brianza",
    subcountry: "Lombardy",
  },
  { country: "Italy", geonameid: 3180601, name: "Capua", subcountry: "Campania" },
  { country: "Italy", geonameid: 3180733, name: "Capannori", subcountry: "Tuscany" },
  { country: "Italy", geonameid: 3180758, name: "Cant\u00f9", subcountry: "Lombardy" },
  {
    country: "Italy",
    geonameid: 3180792,
    name: "Canosa di Puglia",
    subcountry: "Apulia",
  },
  { country: "Italy", geonameid: 3180991, name: "Campobasso", subcountry: "Molise" },
  { country: "Italy", geonameid: 3181018, name: "Campi Bisenzio", subcountry: "Tuscany" },
  { country: "Italy", geonameid: 3181125, name: "Camaiore", subcountry: "Tuscany" },
  { country: "Italy", geonameid: 3181258, name: "Caivano", subcountry: "Campania" },
  { country: "Italy", geonameid: 3181355, name: "Busto Arsizio", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3181359, name: "Bussolengo", subcountry: "Veneto" },
  { country: "Italy", geonameid: 3181471, name: "Brusciano", subcountry: "Campania" },
  { country: "Italy", geonameid: 3181495, name: "Brugherio", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3181528, name: "Brindisi", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3181548, name: "Bresso", subcountry: "Lombardy" },
  {
    country: "Italy",
    geonameid: 3181550,
    name: "Bressanone",
    subcountry: "Trentino-Alto Adige",
  },
  { country: "Italy", geonameid: 3181554, name: "Brescia", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3181631, name: "Bra", subcountry: "Piedmont" },
  {
    country: "Italy",
    geonameid: 3181641,
    name: "Bovisio-Masciago",
    subcountry: "Lombardy",
  },
  { country: "Italy", geonameid: 3181683, name: "Boscoreale", subcountry: "Campania" },
  { country: "Italy", geonameid: 3181790, name: "Borgomanero", subcountry: "Piedmont" },
  {
    country: "Italy",
    geonameid: 3181913,
    name: "Bolzano",
    subcountry: "Trentino-Alto Adige",
  },
  { country: "Italy", geonameid: 3181928, name: "Bologna", subcountry: "Emilia-Romagna" },
  { country: "Italy", geonameid: 3181931, name: "Bollate", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3181995, name: "Bitonto", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3182007, name: "Bisceglie", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3182043, name: "Biella", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 3182164, name: "Bergamo", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3182179, name: "Benevento", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182210, name: "Belluno", subcountry: "Veneto" },
  { country: "Italy", geonameid: 3182272, name: "Battipaglia", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182289, name: "Bastia umbra", subcountry: "Umbria" },
  {
    country: "Italy",
    geonameid: 3182297,
    name: "Bassano del Grappa",
    subcountry: "Veneto",
  },
  { country: "Italy", geonameid: 3182340, name: "Barletta", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3182351, name: "Bari", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3182361, name: "Bareggio", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3182518, name: "Bagnoli", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182599, name: "Bacoli", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182636, name: "Avezzano", subcountry: "Abruzzo" },
  { country: "Italy", geonameid: 3182640, name: "Aversa", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182650, name: "Avellino", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182714, name: "Asti", subcountry: "Piedmont" },
  {
    country: "Italy",
    geonameid: 3182749,
    name: "Ascoli Piceno",
    subcountry: "The Marches",
  },
  { country: "Italy", geonameid: 3182757, name: "Arzignano", subcountry: "Veneto" },
  { country: "Italy", geonameid: 3182765, name: "Arzano", subcountry: "Campania" },
  { country: "Italy", geonameid: 3182851, name: "Ariccia", subcountry: "Latium" },
  { country: "Italy", geonameid: 3182884, name: "Arezzo", subcountry: "Tuscany" },
  { country: "Italy", geonameid: 3182886, name: "Arese", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3182897, name: "Ardea", subcountry: "Latium" },
  { country: "Italy", geonameid: 3182904, name: "Arcore", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3182957, name: "Aprilia", subcountry: "Latium" },
  { country: "Italy", geonameid: 3182997, name: "Aosta", subcountry: "Aosta Valley" },
  { country: "Italy", geonameid: 3183005, name: "Anzio", subcountry: "Latium" },
  { country: "Italy", geonameid: 3183063, name: "Angri", subcountry: "Campania" },
  { country: "Italy", geonameid: 3183072, name: "Andria", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3183089, name: "Ancona", subcountry: "The Marches" },
  { country: "Italy", geonameid: 3183178, name: "Altamura", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3183187, name: "Alpignano", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 3183284, name: "Alghero", subcountry: "Sardinia" },
  { country: "Italy", geonameid: 3183299, name: "Alessandria", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 3183319, name: "Albignasego", subcountry: "Veneto" },
  { country: "Italy", geonameid: 3183343, name: "Albenga", subcountry: "Liguria" },
  { country: "Italy", geonameid: 3183356, name: "Albano Laziale", subcountry: "Latium" },
  { country: "Italy", geonameid: 3183364, name: "Alba", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 3183412, name: "Agropoli", subcountry: "Campania" },
  { country: "Italy", geonameid: 3183455, name: "Afragola", subcountry: "Campania" },
  { country: "Italy", geonameid: 3183472, name: "Adelfia", subcountry: "Apulia" },
  { country: "Italy", geonameid: 3183490, name: "Acqui Terme", subcountry: "Piedmont" },
  {
    country: "Italy",
    geonameid: 3183494,
    name: "Acquaviva delle Fonti",
    subcountry: "Apulia",
  },
  {
    country: "Italy",
    geonameid: 3183539,
    name: "Acilia-Castel Fusano-Ostia Antica",
    subcountry: "Latium",
  },
  { country: "Italy", geonameid: 3183541, name: "Acerra", subcountry: "Campania" },
  { country: "Italy", geonameid: 3183573, name: "Abbiategrasso", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 3183587, name: "Abano Terme", subcountry: "Veneto" },
  { country: "Italy", geonameid: 3219114, name: "Spinea-Orgnano", subcountry: "Veneto" },
  { country: "Italy", geonameid: 6457398, name: "Verbania", subcountry: "Piedmont" },
  { country: "Italy", geonameid: 6534216, name: "Lumezzane", subcountry: "Lombardy" },
  {
    country: "Italy",
    geonameid: 6534228,
    name: "Guidonia Montecelio",
    subcountry: "Latium",
  },
  { country: "Italy", geonameid: 6534232, name: "Lamezia Terme", subcountry: "Calabria" },
  {
    country: "Italy",
    geonameid: 6534234,
    name: "Caronno Pertusella",
    subcountry: "Lombardy",
  },
  {
    country: "Italy",
    geonameid: 6534235,
    name: "Cassano Magnago",
    subcountry: "Lombardy",
  },
  {
    country: "Italy",
    geonameid: 6534252,
    name: "San Felice A Cancello",
    subcountry: "Campania",
  },
  {
    country: "Italy",
    geonameid: 6534253,
    name: "San Nicola la Strada",
    subcountry: "Campania",
  },
  { country: "Italy", geonameid: 6534256, name: "Quarto", subcountry: "Campania" },
  {
    country: "Italy",
    geonameid: 6534264,
    name: "Orta di Atella",
    subcountry: "Campania",
  },
  { country: "Italy", geonameid: 6534267, name: "Casavatore", subcountry: "Campania" },
  { country: "Italy", geonameid: 6534268, name: "Volla", subcountry: "Campania" },
  {
    country: "Italy",
    geonameid: 6534275,
    name: "Gravina di Catania",
    subcountry: "Sicily",
  },
  {
    country: "Italy",
    geonameid: 6534280,
    name: "Cesano Boscone",
    subcountry: "Lombardy",
  },
  { country: "Italy", geonameid: 6534284, name: "Tor Lupara", subcountry: "Latium" },
  { country: "Italy", geonameid: 6620312, name: "Torvaianica", subcountry: "Latium" },
  {
    country: "Italy",
    geonameid: 8224092,
    name: "Bellaria-Igea Marina",
    subcountry: "Emilia-Romagna",
  },
  { country: "Italy", geonameid: 8378910, name: "Villanova", subcountry: "Latium" },
  {
    country: "Italy",
    geonameid: 8394392,
    name: "Marina di Ardea-Tor San Lorenzo",
    subcountry: "Latium",
  },
  { country: "Italy", geonameid: 8948703, name: "San Paolo", subcountry: "Apulia" },
  {
    country: "Italy",
    geonameid: 8948704,
    name: "Monterusciello",
    subcountry: "Campania",
  },
  { country: "Italy", geonameid: 8948705, name: "Romano Banco", subcountry: "Lombardy" },
  { country: "Italy", geonameid: 8948706, name: "Casa Santa", subcountry: "Sicily" },
  { country: "Italy", geonameid: 8948708, name: "Arpino", subcountry: "Campania" },
  { country: "Italy", geonameid: 8948709, name: "Paolo VI", subcountry: "Apulia" },
  {
    country: "Italy",
    geonameid: 9003711,
    name: "Corigliano Scalo",
    subcountry: "Calabria",
  },
  {
    country: "Jersey",
    geonameid: 3042091,
    name: "Saint Helier",
    subcountry: "St Helier",
  },
  {
    country: "Jamaica",
    geonameid: 3488465,
    name: "Spanish Town",
    subcountry: "Saint Catherine",
  },
  {
    country: "Jamaica",
    geonameid: 3488613,
    name: "Savanna-la-Mar",
    subcountry: "Westmoreland",
  },
  {
    country: "Jamaica",
    geonameid: 3488981,
    name: "Portmore",
    subcountry: "Saint Catherine",
  },
  {
    country: "Jamaica",
    geonameid: 3489227,
    name: "Old Harbour",
    subcountry: "Saint Catherine",
  },
  {
    country: "Jamaica",
    geonameid: 3489297,
    name: "New Kingston",
    subcountry: "Saint Andrew",
  },
  {
    country: "Jamaica",
    geonameid: 3489460,
    name: "Montego Bay",
    subcountry: "Saint James",
  },
  { country: "Jamaica", geonameid: 3489523, name: "May Pen", subcountry: "Clarendon" },
  {
    country: "Jamaica",
    geonameid: 3489577,
    name: "Mandeville",
    subcountry: "Manchester",
  },
  {
    country: "Jamaica",
    geonameid: 3489760,
    name: "Linstead",
    subcountry: "Saint Catherine",
  },
  { country: "Jamaica", geonameid: 3489854, name: "Kingston", subcountry: "Kingston" },
  {
    country: "Jamaica",
    geonameid: 3490165,
    name: "Half Way Tree",
    subcountry: "Saint Andrew",
  },
  {
    country: "Jordan",
    geonameid: 246013,
    name: "W\u0101d\u012b as S\u012br",
    subcountry: "Amman",
  },
  {
    country: "Jordan",
    geonameid: 246314,
    name: "Umm as Summ\u0101q",
    subcountry: "Amman",
  },
  { country: "Jordan", geonameid: 247105, name: "Sa\u1e29\u0101b", subcountry: "Amman" },
  {
    country: "Jordan",
    geonameid: 248370,
    name: "M\u0101dab\u0101",
    subcountry: "Madaba",
  },
  { country: "Jordan", geonameid: 248382, name: "Ma'an", subcountry: "Ma\u2019an" },
  { country: "Jordan", geonameid: 248414, name: "Kurayyimah", subcountry: "Irbid" },
  { country: "Jordan", geonameid: 248803, name: "Judita", subcountry: "Irbid" },
  { country: "Jordan", geonameid: 248875, name: "Jarash", subcountry: "Jerash" },
  { country: "Jordan", geonameid: 248923, name: "\u2018Izr\u0101", subcountry: "Karak" },
  { country: "Jordan", geonameid: 248946, name: "Irbid", subcountry: "Irbid" },
  { country: "Jordan", geonameid: 250090, name: "Zarqa", subcountry: "Zarqa" },
  { country: "Jordan", geonameid: 250152, name: "Ayd\u016bn", subcountry: "Irbid" },
  {
    country: "Jordan",
    geonameid: 250198,
    name: "A\u0163 \u0162af\u012blah",
    subcountry: "Tafielah",
  },
  { country: "Jordan", geonameid: 250258, name: "As Sal\u0163", subcountry: "Balqa" },
  { country: "Jordan", geonameid: 250267, name: "Safi", subcountry: "Karak" },
  { country: "Jordan", geonameid: 250336, name: "Ar Ramth\u0101", subcountry: "Irbid" },
  { country: "Jordan", geonameid: 250420, name: "\u2018Anjarah", subcountry: "Ajlun" },
  { country: "Jordan", geonameid: 250441, name: "Amman", subcountry: "Amman" },
  { country: "Jordan", geonameid: 250461, name: "Al Quwaysimah", subcountry: "Amman" },
  { country: "Jordan", geonameid: 250582, name: "Mafraq", subcountry: "Mafraq" },
  {
    country: "Jordan",
    geonameid: 250624,
    name: "Q\u012br Mo\u0101v",
    subcountry: "Ma\u2019an",
  },
  { country: "Jordan", geonameid: 250637, name: "Al Jubayhah", subcountry: "Amman" },
  { country: "Jordan", geonameid: 250774, name: "Aqaba", subcountry: "Aqaba" },
  { country: "Jordan", geonameid: 250799, name: "\u2018Ajl\u016bn", subcountry: "Ajlun" },
  { country: "Jordan", geonameid: 6946409, name: "Karak City", subcountry: "Karak" },
  { country: "Jordan", geonameid: 7838895, name: "Russeifa", subcountry: "Zarqa" },
  { country: "Japan", geonameid: 1847947, name: "Shing\u016b", subcountry: "Wakayama" },
  { country: "Japan", geonameid: 1847963, name: "Atsugi", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1847966, name: "Akashi", subcountry: "Hy\u014dgo" },
  { country: "Japan", geonameid: 1847968, name: "Zushi", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1848004, name: "Zama", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1848016, name: "Yuza", subcountry: "Yamagata" },
  { country: "Japan", geonameid: 1848055, name: "Gero", subcountry: "Gifu" },
  { country: "Japan", geonameid: 1848087, name: "Yukuhashi", subcountry: "Fukuoka" },
  { country: "Japan", geonameid: 1848096, name: "Y\u016bki", subcountry: "Ibaraki" },
  { country: "Japan", geonameid: 1848113, name: "Yugawara", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1848188, name: "Yoshikawa", subcountry: "Saitama" },
  { country: "Japan", geonameid: 1848194, name: "Yoshii", subcountry: "Gunma" },
  {
    country: "Japan",
    geonameid: 1848210,
    name: "Yoshida-kasugach\u014d",
    subcountry: "Niigata",
  },
  { country: "Japan", geonameid: 1848243, name: "Yorii", subcountry: "Saitama" },
  { country: "Japan", geonameid: 1848254, name: "Yono", subcountry: "Saitama" },
  { country: "Japan", geonameid: 1848277, name: "Yonago", subcountry: "Tottori" },
  { country: "Japan", geonameid: 1848313, name: "Yokosuka", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1848354, name: "Yokohama", subcountry: "Kanagawa" },
  { country: "Japan", geonameid: 1848373, name: "Yokkaichi", subcountry: "Mie" },
  {
    country: "Japan",
    geonameid: 1848382,
    name: "Youkaichi",
    subcountry: "Shiga Prefecture",
  },
  { country: "Japan", geonameid: 1848439, name: "Yawata", subcountry: "Kyoto" },
  { country: "Japan", geonameid: 1848445, name: "Yatsushiro", subcountry: "Kumamoto" },
  {
    country: "Japan",
    geonameid: 1848447,
    name: "Yatsuomachi-higashikumisaka",
    subcountry: "Toyama",
  },
  { country: "Japan", geonameid: 1848482, name: "Yasugich\u014d", subcountry: "Shimane" },
  { country: "Japan", geonameid: 1848498, name: "Yashiro", subcountry: "Hy\u014dgo" },
  { country: "Japan", geonameid: 1848499, name: "Yashio-shi", subcountry: "Saitama" },
  { country: "Japan", geonameid: 1848522, name: "Yao", subcountry: "\u014csaka" },
  { country: "Japan", geonameid: 1848550, name: "Yanai", subcountry: "Yamaguchi" },
  { country: "Japan", geonameid: 1848573, name: "Yanagawa", subcountry: "Fukuoka" },
  {
    country: "Japan",
    geonameid: 1848633,
    name: "Yamazakich\u014d-nakabirose",
    subcountry: "Hy\u014dgo",
  },
  { country: "Japan", geonameid: 1848689, name: "Yamaguchi", subcountry: "Yamaguchi" },
  { country: "Japan", geonameid: 1848705, name: "Yamaga", subcountry: "Kumamoto" },
  { country: "Japan", geonameid: 1848774, name: "Yaizu", subcountry: "Shizuoka" },
  { country: "Japan", geonameid: 1848776, name: "Yaita", subcountry: "Tochigi" },
  { country: "Japan", geonameid: 1848933, name: "Wakimachi", subcountry: "Tokushima" },
  { country: "Japan", geonameid: 1849053, name: "Utsunomiya", subcountry: "Tochigi" },
  { country: "Japan", geonameid: 1849069, name: "Uto", subcountry: "Kumamoto" },
  { country: "Japan", geonameid: 1849094, name: "Usuki", subcountry: "Oita" },
  { country: "Japan", geonameid: 1849154, name: "Ushibuka", subcountry: "Kumamoto" },
  {
    country: "Japan",
    geonameid: 1849183,
    name: "Ureshinomachi-shimojuku",
    subcountry: "Saga Prefecture",
  },
  { country: "Japan", geonameid: 1849186, name: "Urayasu", subcountry: "Tokyo" },
  { country: "Japan", geonameid: 1849237, name: "Uozu", subcountry: "Toyama" },
  { country: "Japan", geonameid: 1849299, name: "Umi", subcountry: "Fukuoka" },
  { country: "Japan", geonameid: 1849367, name: "Ujiie", subcountry: "Tochigi" },
  { country: "Japan", geonameid: 1849372, name: "Uji", subcountry: "Kyoto" },
  { country: "Japan", geonameid: 1849407, name: "Uenohara", subcountry: "Yamanashi" },
  { country: "Japan", geonameid: 1849414, name: "Ueno-ebisumachi", subcountry: "Mie" },
  { country: "Japan", geonameid: 1849424, name: "Ueki", subcountry: "Kumamoto" },
  { country: "Japan", geonameid: 1849429, name: "Ueda", subcountry: "Nagano" },
  { country: "Japan", geonameid: 1849498, name: "Ube", subcountry: "Yamaguchi" },
  { country: "Japan", geonameid: 1849519, name: "Tsuyama", subcountry: "Okayama" },
  { country: "Japan", geonameid: 1849539, name: "Tsushima", subcountry: "Aichi" },
  { country: "Japan", geonameid: 1849561, name: "Tsurusaki", subcountry: "Oita" },
  { country: "Japan", geonameid: 1849563, name: "Tsuruoka", subcountry: "Yamagata" },
  {
    country: "Japan",
    geonameid: 1849584,
    name: "Tsurugi-asahimachi",
    subcountry: "Ishikawa",
  },
  { country: "Japan", geonameid: 1849592, name: "Tsuruga", subcountry: "Fukui" },
  { country: "Japan", geonameid: 1849647, name: "Tsuma", subcountry: "Miyazaki" },
  { country: "Japan", geonameid: 1849661, name: "Tsukumiura", subcountry: "Oita" },
  { country: "Japan", geonameid: 1849706, name: "Tsukawaki", subcountry: "Oita" },
  { country: "Japan", geonameid: 1849782, name: "Tsubata", subcountry: "Ishikawa" },
  { country: "Japan", geonameid: 1849788, name: "Tsubame", subcountry: "Niigata" },
  { country: "Japan", geonameid: 1849796, name: "Tsu", subcountry: "Mie" },
  { country: "Japan", geonameid: 1849814, name: "Toyota", subcountry: "Aichi" },
];
